language: python
python:
- '2.7'

install:
- pip install -r requirements.txt

script:
- flake8
- ./scripts/xgettext.sh

before_deploy:
- npm install -g harp
- npm install -g surge
- make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: script.elementum.nova-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: Nemiroff/script.elementum.nova
    tags: true
